### ISSUE TITLE
Refero component loading global styles that are targeting all the checkboxes in the application.

### ISSUE THREAD

**Issue by kajami** [helsenorge/refero#113]
Hello,

I noticed that when I take ReferoContainer in use it will loads styles globally all around the application and there are css that is targeting all the checkboxes. Could this checkbox be styled so that it would not target all the checkboxes? These style comes from @helsenorge/form library (@helsenorge/form/components/checkbox/styles.scss) Below is the styles that are loaded globally.

input[type=checkbox] {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

input[type=checkbox] + label {
  cursor: pointer;
  display: block;
  font-size: 18px;
  font-weight: 400;
  margin: 0;
  word-break: break-word;
  hyphens: auto;
  hyphens: auto;
  hyphens: auto;
}

**Comment by andreasnp** [comment]
Hello Kajami, we have looked at this issue and have added it as a bug in our backlog. Thank you for your request.

**Comment by andreasnp** [comment]
Hello Kajami, we have looked at this issue and have added it as a bug in our backlog. Thank you for your request.

**Comment by ruberino** [comment]
Update on this issue: We are currently rewriting refero to use new form componenents. This issue will be resolved. If you want to, you can check the beta versions
