### ISSUE TITLE
npm audit shows vulnerabilities for this package

### ISSUE THREAD

**Issue by Vladymyrdev** [helsenorge/refero#114]
Could you please update the dependencies (marked, node-fetch)?
![image](https://github.com/helsenorge/refero/assets/95679982/413b4fe1-6075-4d1d-80cd-c677b890e3fc)

**Comment by AG-83** [comment]
Fixed

**Comment by imanesaurus** [comment]
![image](https://github.com/helsenorge/refero/assets/2940365/10767375-d2e3-4ce7-a420-5133d5b56dc7)

@AG-83 issue's for marked package still persist on latest upgrade. I had to upgrade the package to `"marked": "^4.0.10"`, fix the vulnerabilities. 
Can we used this version @AG-83 ?

**Comment by AG-83** [comment]
Hi @imanesaurus 
We have looked at the issue and the security issue in Marked package does not affect us and we decided to move this issue back in out backlogs.
