### ISSUE TITLE
@helsenorge refero size

### ISSUE THREAD

**Issue by kajami** [helsenorge/refero#119]
Hello,

I noticed that the refero library and its dependencies are quite big. Those are total of 7.5 MB in the bundle file. It can take a long time to load the application with refero library if you have a poor internet connection. The fhir.js file (@helsenorge\refero\types\fhir.js) that contains the FHIR types takes up most of the space in the bundle (6.36MB). Is there any way that you could optimize the size of this library? Are all the types for example necessary for rendering FHIR Questionnaire?

**Comment by kennethmyhra** [comment]
It's an auto-generated file and could probably be optimized, but it is not something we will prioritize. If you want to give it a shot you are welcome to do so
