### ISSUE TITLE
React 18 Compatibility Issue with @helsenorge/refero

### ISSUE THREAD

**Issue by nsabale7** [helsenorge/refero#216]
The issue is `@helsenorge/refero` package is currently incompatible with React 18. While trying to install the package in a project that uses React 18.3.1, I encountered a dependency conflict.

### Steps to Reproduce

1. Create a new project with React 18.3.1.
2. Run `npm install @helsenorge/refero`.

NPM throws the following error:

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: ccbw@0.1.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   react@"^18.3.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^17.0.2" from @helsenorge/refero@16.0.0-beta21
npm error node_modules/@helsenorge/refero
npm error   @helsenorge/refero@"*" from the root project
```

Can you please consider updating the peer dependency to support React 18 or release a version compatible with React 18.

Thanks

**Comment by ruberino** [comment]
support for react18 will come in the next major version
